[project]
name = "ideogram4_prompter-ComfyUI"
description = "ComfyUI custom nodes for Ideogram 4 Magic Prompt and Ideogram 4 resolution selection"
version = "0.1.1"
license = {text = "LICENSE"}
dependencies = []

[project.urls]
Repository = "https://github.com/Saganaki22/ideogram4_prompter-ComfyUI"
Ideogram = "https://developer.ideogram.ai/api-reference/api-reference/magic-prompt-v4"
ApiKey = "https://ideogram.ai/manage-api"

[tool.comfy]
PublisherId = "saganaki22"
DisplayName = "Ideogram 4 Prompter"
Icon = "https://avatars.githubusercontent.com/u/84208527"
